language: ruby
rvm:
- 2.4.4
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
- cd client && npm install && npm test -- --coverage

after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token cd client && npm run coveralls

services:
- postgresql
notifications:
  email: false
